version: '2.1'

services:
  heroes-node-api:
    image: heroes-node-api
    build: .
    env_file:
      - .env
    # environment:
    #   NODE_ENV: development
    restart: always
    ports:
      - 7777:7777
      - 9229:9229
    command: npm run start_debug
    # command: node --inspect=0.0.0.0:9229 server.js
